FROM python:3.12

WORKDIR /usr/src/app
RUN mkdir -p $WORKDIR/static
RUN mkdir -p $WORKDIR/media

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .


EXPOSE 1213
CMD ["python", "manage.py", "runserver", "1213"]

# CMD ["gunicorn","-b","0.0.0.0:8001","soaqaz.wsgi:application"]